#!/bin/bash

repo=$1
echo $repo
commit_id=$2
echo $commit_id
# git config --global user.name "sunflower0309"
# git config --global user.name "sunflower0309+1s"
# git clone https://github.com/spideruci/primitive-hamcrest.git /home/primitive-hamcrest
# git clone https://github.com/spideruci/tacoco.git /home/tacoco
git clone $repo /home/sut

# cd /home/primitive-hamcrest
# mvn install -DskipITs
# cd /home/tacoco
# mvn install -DskipITs
cd /home/sut
git checkout $commit_id
mvn compile test-compile

/home/tacoco/scripts/run-tacoco /home/sut /home/tacoco
cd /home

python3 ./utilsfordocker.py $3 $4 /home/tacoco/tacoco_output/sut-cov-matrix.json $5 $6
